"""
Simulation & Evaluation Flywheel.

"""
import os
import sys
import json
import uuid
import argparse
import random
import urllib.parse
from dotenv import load_dotenv
import backend.agent.orchestrator as orchestrator_mod
import backend.agent.evaluation_agent as eval_mod
try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    sys.exit("Run: pip install 'psycopg[binary]' --break-system-packages")

sys.path.insert(0, os.path.dirname(__file__))

def _with_query_param(url, key, value):
    parts = urllib.parse.urlsplit(url)
    params = urllib.parse.parse_qsl(parts.query, keep_blank_values=True)
    params = [(k, v) for k, v in params if k != key]
    params.append((key, value))
    return urllib.parse.urlunsplit((parts.scheme, parts.netloc, parts.path, urllib.parse.urlencode(params), parts.fragment))

load_dotenv()  # Injects variables from .env into os.environ
CRDB_URL = os.environ.get("CRDB_URL")
if CRDB_URL and "sslrootcert=" not in CRDB_URL:
    cert_path = "/etc/ssl/cert.pem" if os.path.exists("/etc/ssl/cert.pem") else "system"
    CRDB_URL = _with_query_param(CRDB_URL, "sslrootcert", cert_path)

SCHEMA_ADDITIONS = """
CREATE TABLE IF NOT EXISTS simulation_scenarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_characteristics JSONB,
    customer_story STRING,
    customer_intent STRING,
    source_conversation_id UUID,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS simulation_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scenario_id UUID REFERENCES simulation_scenarios(id),
    conversation_id UUID,
    pass BOOL,
    prompt_version STRING,
    created_at TIMESTAMPTZ DEFAULT now()
);
"""

PUSHBACK_BY_TONE = {
    "frustrated": ["This keeps happening, I'm considering switching to a competitor."],
    "insistent": ["I don't understand why this needs review, just process it now."],
    "polite": ["Oh okay, thank you for explaining."],
    "neutral": ["Alright, how long will that take?"],
}


def generate_scenarios_from_history(conn, n=50):
    """Mine real conversations for scenario seeds.

    Excludes conversations that:
      - have no customer messages (can't form an opener)
      - were themselves generated by a previous simulation run
    Uses the actual first customer message as the opener so the simulator
    starts with a real query, not a potentially-null summary.
    """
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            SELECT c.*,
                   (SELECT content FROM messages
                    WHERE conversation_id = c.id AND role = 'customer'
                    ORDER BY created_at ASC LIMIT 1) AS first_message
            FROM conversations c
            WHERE c.id IN (
                SELECT DISTINCT conversation_id FROM messages WHERE role = 'customer'
            )
            AND c.id NOT IN (
                SELECT conversation_id FROM simulation_runs
                WHERE conversation_id IS NOT NULL
            )
            ORDER BY c.created_at DESC
            LIMIT %s
            """,
            (n,),
        )
        records = cur.fetchall()

    sample = random.sample(records, min(n, len(records)))

    scenarios = []
    with conn.cursor() as cur:
        for r in sample:
            sid = str(uuid.uuid4())
            characteristics = {"behavior": r.get("behavior", "existing"), "tone": r.get("tone")}
            opener = r.get("first_message") or r.get("summary") or "I need help with my order."
            story = r.get("summary") or opener
            cur.execute(
                """INSERT INTO simulation_scenarios
                   (id, customer_characteristics, customer_story, customer_intent, source_conversation_id)
                   VALUES (%s, %s, %s, %s, %s)""",
                (sid, json.dumps(characteristics), story, r["status"], r["id"]),
            )
            scenarios.append({
                "id": sid, **characteristics,
                "customer_id": r["customer_id"],
                "opener": opener,
                "category": r["status"],
            })
    conn.commit()
    return scenarios


class SimulatorAgent:
    """Plays the customer: decides push-back/accept/escalate based on tone,
    caps turns to avoid infinite loops."""
    def __init__(self, max_turns=3):
        self.max_turns = max_turns

    def next_customer_turn(self, scenario, turn_number, last_agent_response):
        # TODO: could add more sophisticated logic here, e.g. based on the agent's last response
        if turn_number >= self.max_turns:
            return None  # end conversation
        tone = scenario.get("tone", "neutral")
        # Real AWS Bedrock (Claude) plays the customer, tone-driven, against
        # the LIVE orchestrator — so simulated traffic exercises the same
        # graph/guardrail/judge as production. Falls back to the canned
        # pushback lines if Bedrock is unreachable, keeping batches runnable.
        try:
            from backend.utilis.bedrock_client import get_llm
            llm = get_llm()
            if llm.is_live:
                system = (
                    f"You are the CUSTOMER in an e-commerce support chat. Your "
                    f"tone is {tone}. Push back realistically if the agent's "
                    f"reply doesn't fully solve your problem; if it does, reply "
                    f"with just 'RESOLVED'. Keep it to one short message."
                )
                user = (f"Your original issue: {scenario.get('opener','')}\n"
                        f"Agent just said: {last_agent_response}\nYour reply:")
                txt = llm.complete(system, user, max_tokens=80).text.strip()
                return None if txt.upper().startswith("RESOLVED") else txt
        except Exception:
            pass
        if random.random() < 0.5:
            return random.choice(PUSHBACK_BY_TONE.get(tone, PUSHBACK_BY_TONE["neutral"]))
        return None


def run_simulation(conn, scenario, prompt_version="v1"):
    # Reuse a stored result for this (scenario, prompt_version) pair so re-runs
    # of the flywheel don't re-exercise scenarios that already have a verdict.
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """SELECT pass FROM simulation_runs
               WHERE scenario_id = %s AND prompt_version = %s
               ORDER BY created_at DESC LIMIT 1""",
            (scenario["id"], prompt_version),
        )
        existing = cur.fetchone()
    if existing is not None:
        print(f"[sim] reusing stored result for scenario {scenario['id'][:8]} "
              f"@ {prompt_version}: pass={existing['pass']}")
        return existing["pass"]

    graph = orchestrator_mod.build_graph(conn).compile()
    conversation_id = orchestrator_mod.create_conversation(conn, customer_id=scenario["customer_id"])
    simulator = SimulatorAgent()

    query = scenario["opener"]
    # is_simulated=True suppresses log_message writes so simulated turns
    # don't pollute the messages table that real conversation history queries.
    state = {
        "conversation_id": conversation_id,
        "customer_id": scenario["customer_id"],
        "query": query,
        "escalated": False,
        "is_simulated": True,
    }

    turn = 0
    result = graph.invoke(state, config={"configurable": {"thread_id": conversation_id}})
    while True:
        next_msg = simulator.next_customer_turn(scenario, turn, result.get("final_response"))
        if not next_msg:
            break
        turn += 1
        result["query"] = next_msg
        result["is_simulated"] = True  # keep flag across turns
        result = graph.invoke(result, config={"configurable": {"thread_id": conversation_id}})

    verdict = eval_mod.evaluate_conversation(conn, conversation_id, is_simulated=True)
    passed = all(v for k, v in verdict.items()
                 if k in ("retrieval_correctness", "response_accuracy", "grammar_language_ok",
                          "coherence_to_context", "relevance_to_request") and v is not None)

    with conn.cursor() as cur:
        cur.execute(
            """INSERT INTO simulation_runs (scenario_id, conversation_id, pass, prompt_version)
               VALUES (%s, %s, %s, %s)""",
            (scenario["id"], conversation_id, passed, prompt_version),
        )
    conn.commit()
    return passed


def gate_deploy(pass_rate, baseline):
    if pass_rate < baseline:
        print(f"BLOCKED: pass rate {pass_rate:.2%} < baseline {baseline:.2%}")
        sys.exit(1)
    print(f"OK: pass rate {pass_rate:.2%} >= baseline {baseline:.2%}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, default=50)
    parser.add_argument("--baseline", type=float, default=0.85)
    parser.add_argument("--prompt-version", default="v1")
    args = parser.parse_args()

    if not CRDB_URL:
        sys.exit("Set CRDB_URL env var first.")

    with psycopg.connect(CRDB_URL) as conn:
        # with conn.cursor() as cur:
        #     cur.execute(SCHEMA_ADDITIONS)
        # conn.commit()

        scenarios = generate_scenarios_from_history(conn, n=args.n)
        results = [run_simulation(conn, s, prompt_version=args.prompt_version) for s in scenarios]
        pass_rate = sum(results) / len(results) if results else 0.0

        print(f"Ran {len(results)} simulations, pass rate {pass_rate:.2%}")
        gate_deploy(pass_rate, args.baseline)
